[package]
name = "wallet-pass"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
fs_extra = "1.2"
tempfile = "3.2"
walkdir = "2.3"
zip = { version = "0.5", features = ["deflate"] }
openssl = "0.10"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
